import type { Anuncio } from "../types";
import { dia } from "./datas";

/**
 * Anúncios demonstrativos. Regra do produto: apenas `status: "publicado"` com
 * `visibilidade: "publico"` aparece no site institucional — ver `anunciosPublicos`
 * em `lib/store.tsx`.
 */
export const anuncios: Anuncio[] = [
  {
    id: "an1",
    codigo: "AN-001",
    imovelId: "im1",
    titulo: "Casa Reserva da Pedra — arquitetura atemporal na Pedra Branca",
    subtitulo: "330 m² de projeto autoral em condomínio fechado no bairro planejado",
    descricaoComercial:
      "Três suítes, piscina aquecida e um living que se abre por completo para o deck. Uma casa desenhada para receber e para o silêncio de todo dia.",
    destaques: [
      "3 suítes com varanda",
      "Piscina aquecida e espaço gourmet",
      "Automação e aquecimento solar",
      "Terreno de 512 m² em condomínio fechado",
    ],
    capaIndice: 0,
    ordemGaleria: [0, 1, 2, 3, 4, 5],
    selos: ["exclusivo"],
    status: "publicado",
    visibilidade: "publico",
    publicarEm: dia(-30),
    destaqueHome: true,
    metricas: { visualizacoes: 3142, contatos: 27, conversoes: 6 },
    corretorId: "u2",
    criadoEm: dia(-32),
    atualizadoEm: dia(-12),
  },
  {
    id: "an2",
    codigo: "AN-002",
    imovelId: "im2",
    titulo: "Casa Jardim Eldorado — condomínio fechado em rua silenciosa",
    subtitulo: "214 m² com piscina, jardim projetado e escritório de entrada independente",
    descricaoComercial:
      "Espaço de casa com a segurança de condomínio, a dez minutos do acesso à BR-101. Três dormitórios e um escritório que funciona sozinho.",
    destaques: [
      "214 m² com 3 dormitórios",
      "Piscina e churrasqueira coberta",
      "Escritório com acesso independente",
      "Portaria 24 horas",
    ],
    capaIndice: 0,
    ordemGaleria: [0, 1, 2, 3, 4],
    selos: ["exclusivo", "oportunidade"],
    status: "publicado",
    visibilidade: "publico",
    publicarEm: dia(-30),
    destaqueHome: true,
    metricas: { visualizacoes: 2418, contatos: 19, conversoes: 4 },
    corretorId: "u1",
    criadoEm: dia(-31),
    atualizadoEm: dia(-18),
  },
  {
    id: "an3",
    codigo: "AN-003",
    imovelId: "im3",
    titulo: "Apartamento mobiliado no Pagani — Residencial Taranto",
    subtitulo: "74 m² prontos para morar, com suíte e sacada com churrasqueira",
    descricaoComercial:
      "Mobiliado e equipado, no andar alto, com toda a estrutura do Pagani na mesma quadra. Basta chegar com as malas.",
    destaques: [
      "Mobiliado e equipado",
      "2 dormitórios, sendo 1 suíte",
      "Sacada com churrasqueira",
      "Academia e salão de festas",
    ],
    capaIndice: 0,
    ordemGaleria: [0, 1, 2, 3],
    selos: ["oportunidade"],
    status: "publicado",
    visibilidade: "publico",
    publicarEm: dia(-26),
    destaqueHome: true,
    metricas: { visualizacoes: 1876, contatos: 22, conversoes: 3 },
    corretorId: "u2",
    criadoEm: dia(-27),
    atualizadoEm: dia(-10),
  },
  {
    id: "an4",
    codigo: "AN-004",
    imovelId: "im4",
    titulo: "Cobertura Vista Baía Sul — terraço com piscina na Ponte do Imaruim",
    subtitulo: "218 m² duplex com vista permanente para a baía e a ponte Hercílio Luz",
    descricaoComercial:
      "O último pavimento inteiro do edifício, com terraço de 80 m², piscina, hidromassagem e reforma integral concluída em 2025.",
    destaques: [
      "Terraço privativo de 80 m²",
      "3 suítes",
      "Vista permanente para a Baía Sul",
      "3 vagas cobertas",
    ],
    capaIndice: 0,
    ordemGaleria: [0, 1, 2, 3, 4],
    selos: ["exclusivo", "lancamento"],
    status: "publicado",
    visibilidade: "publico",
    publicarEm: dia(-22),
    destaqueHome: true,
    metricas: { visualizacoes: 4210, contatos: 31, conversoes: 5 },
    corretorId: "u1",
    criadoEm: dia(-24),
    atualizadoEm: dia(-8),
  },
  {
    id: "an5",
    codigo: "AN-005",
    imovelId: "im5",
    titulo: "Apartamento semi mobiliado no Passa Vinte — Nova Cidade",
    subtitulo: "68 m² com dois dormitórios e suíte, para venda ou locação",
    descricaoComercial:
      "Planejados em todos os ambientes e vaga coberta, em região consolidada com escolas e mercado a caminhada.",
    destaques: [
      "Semi mobiliado com planejados",
      "2 dormitórios, sendo 1 suíte",
      "Vaga coberta e depósito",
      "Disponível para venda ou locação",
    ],
    capaIndice: 0,
    ordemGaleria: [0, 1, 2, 3],
    selos: [],
    status: "publicado",
    visibilidade: "publico",
    publicarEm: dia(-19),
    destaqueHome: false,
    metricas: { visualizacoes: 1204, contatos: 14, conversoes: 2 },
    corretorId: "u3",
    criadoEm: dia(-20),
    atualizadoEm: dia(-19),
  },
  {
    id: "an6",
    codigo: "AN-006",
    imovelId: "im7",
    titulo: "Terreno Pedra Branca — lote plano de esquina",
    subtitulo: "420 m² prontos para construir, com infraestrutura completa",
    descricaoComercial:
      "Um dos últimos lotes de esquina do quarteirão. Topografia plana dispensa contenção e reduz o custo de fundação.",
    destaques: [
      "420 m² em esquina",
      "Topografia integralmente plana",
      "Fibra óptica e calçada entregues",
      "Bairro planejado com universidade e comércio",
    ],
    capaIndice: 0,
    ordemGaleria: [0, 1],
    selos: ["oportunidade"],
    status: "publicado",
    visibilidade: "publico",
    publicarEm: dia(-16),
    destaqueHome: false,
    metricas: { visualizacoes: 932, contatos: 11, conversoes: 2 },
    corretorId: "u3",
    criadoEm: dia(-17),
    atualizadoEm: dia(-16),
  },
  {
    id: "an7",
    codigo: "AN-007",
    imovelId: "im8",
    titulo: "Sala comercial no Hogar Corporate — investimento com liquidez",
    subtitulo: "20,60 m² no centro de Palhoça, com vaga privativa",
    descricaoComercial:
      "Perfil de imóvel com demanda constante por locação e baixa vacância, ao lado dos órgãos públicos e do comércio central.",
    destaques: [
      "20,60 m² prontos para o layout do inquilino",
      "Vaga privativa na garagem",
      "Segurança 24 horas",
      "Venda ou locação",
    ],
    capaIndice: 0,
    ordemGaleria: [0, 1, 2],
    selos: ["oportunidade"],
    status: "publicado",
    visibilidade: "publico",
    publicarEm: dia(-14),
    destaqueHome: false,
    metricas: { visualizacoes: 741, contatos: 9, conversoes: 1 },
    corretorId: "u2",
    criadoEm: dia(-15),
    atualizadoEm: dia(-14),
  },
  {
    id: "an8",
    codigo: "AN-008",
    imovelId: "im9",
    titulo: "Apartamento frente mar na Enseada de Brito",
    subtitulo: "132 m² com três dormitórios e vista permanente para o mar",
    descricaoComercial:
      "Apenas dois apartamentos por andar e uma vista que não pode ser obstruída. Living em L e sacada com churrasqueira.",
    destaques: [
      "Frente mar, vista permanente",
      "3 dormitórios, sendo 2 suítes",
      "2 apartamentos por andar",
      "2 vagas cobertas",
    ],
    capaIndice: 0,
    ordemGaleria: [0, 1, 2, 3, 4],
    selos: ["exclusivo"],
    status: "publicado",
    visibilidade: "publico",
    publicarEm: dia(-11),
    destaqueHome: true,
    metricas: { visualizacoes: 2890, contatos: 24, conversoes: 4 },
    corretorId: "u4",
    criadoEm: dia(-12),
    atualizadoEm: dia(-11),
  },
  {
    id: "an9",
    codigo: "AN-009",
    imovelId: "im10",
    titulo: "Casa de campo na Guarda do Cubatão — 5.200 m² de terreno",
    subtitulo: "Pomar formado, nascente própria e vista para a Serra do Tabuleiro",
    descricaoComercial:
      "Uma casa feita para receber, a 25 minutos do centro de Palhoça. Quatro dormitórios, casa de caseiro e lazer completo.",
    destaques: [
      "320 m² em terreno de 5.200 m²",
      "Nascente e poço artesiano",
      "Pomar formado e piscina",
      "Casa de caseiro independente",
    ],
    capaIndice: 0,
    ordemGaleria: [0, 1, 2, 3],
    selos: [],
    status: "publicado",
    visibilidade: "publico",
    publicarEm: dia(-7),
    destaqueHome: false,
    metricas: { visualizacoes: 1533, contatos: 16, conversoes: 2 },
    corretorId: "u3",
    criadoEm: dia(-8),
    atualizadoEm: dia(-7),
  },
  {
    id: "an10",
    codigo: "AN-010",
    imovelId: "im12",
    titulo: "Sítio Santa Helena — 9,6 hectares em Santo Amaro da Imperatriz",
    subtitulo: "Sede restaurada, lagoa própria e rio de águas limpas na divisa",
    descricaoComercial:
      "Propriedade de 96.000 m² com sede de 420 m², casa de hóspedes, pomar formado e pastagem, a 35 minutos de Florianópolis.",
    destaques: [
      "9,6 hectares",
      "Sede restaurada com 5 dormitórios",
      "Lagoa e nascente próprias",
      "Documentação regular",
    ],
    capaIndice: 0,
    ordemGaleria: [0, 1, 2, 3],
    selos: ["exclusivo"],
    status: "revisao",
    visibilidade: "publico",
    destaqueHome: false,
    metricas: { visualizacoes: 0, contatos: 0, conversoes: 0 },
    corretorId: "u1",
    criadoEm: dia(-4),
    atualizadoEm: dia(-2),
  },
  {
    id: "an11",
    codigo: "AN-011",
    imovelId: "im6",
    titulo: "Casa Bosque das Mangueiras — Forquilhinhas, São José",
    subtitulo: "268 m² com piscina, horta e terreno arborizado",
    descricaoComercial:
      "Projeto implantado ao redor das mangueiras antigas do terreno, garantindo sombra natural na área de lazer o verão inteiro.",
    destaques: ["268 m² em 480 m² de terreno", "Piscina e espaço gourmet", "Horta produtiva", "3 vagas"],
    capaIndice: 0,
    ordemGaleria: [0, 1, 2, 3],
    selos: [],
    status: "pausado",
    visibilidade: "privado",
    destaqueHome: false,
    metricas: { visualizacoes: 1987, contatos: 21, conversoes: 3 },
    corretorId: "u4",
    criadoEm: dia(-60),
    atualizadoEm: dia(-9),
  },
  {
    id: "an12",
    codigo: "AN-012",
    imovelId: "im11",
    titulo: "Apartamento no Parque da Ponte — a 400 m do terminal",
    subtitulo: "48 m² semi mobiliado com vaga coberta na Ponte do Imaruim",
    descricaoComercial:
      "Prédio reformado em 2024, com playground e portaria 24 horas. Acesso direto a Florianópolis pelo terminal.",
    destaques: ["48 m² semi mobiliado", "2 dormitórios", "Vaga coberta", "400 m do terminal"],
    capaIndice: 0,
    ordemGaleria: [0, 1],
    selos: ["alugado"],
    status: "expirado",
    visibilidade: "publico",
    publicarEm: dia(-120),
    expirarEm: dia(-21),
    destaqueHome: false,
    metricas: { visualizacoes: 2240, contatos: 34, conversoes: 1 },
    corretorId: "u2",
    criadoEm: dia(-125),
    atualizadoEm: dia(-21),
  },
  {
    id: "an13",
    codigo: "AN-013",
    imovelId: "im1",
    titulo: "Reserva da Pedra — campanha de verão",
    subtitulo: "Versão alternativa do anúncio, em preparação",
    descricaoComercial:
      "Rascunho de campanha sazonal com book fotográfico noturno. Aguarda aprovação das novas fotos.",
    destaques: ["Book noturno", "Vídeo aéreo"],
    capaIndice: 1,
    ordemGaleria: [1, 0, 2, 3],
    selos: ["exclusivo"],
    status: "rascunho",
    visibilidade: "privado",
    destaqueHome: false,
    metricas: { visualizacoes: 0, contatos: 0, conversoes: 0 },
    corretorId: "u2",
    criadoEm: dia(-3),
    atualizadoEm: dia(-1),
  },
];

export const anuncioPorId = (id: string) => anuncios.find((a) => a.id === id);
