import type { Cliente } from "../types";
import { dia, momento } from "./datas";

/**
 * Clientes demonstrativos: c1–c6 são compradores/locatários em diferentes
 * etapas do funil; c7–c18 são os proprietários vinculados aos imóveis.
 */
export const clientes: Cliente[] = [
  {
    id: "c1",
    nome: "Marina Azevedo",
    documento: "38427199054",
    telefone: "48991234501",
    whatsapp: "48991234501",
    email: "marina.azevedo@email.com.br",
    endereco: "Rua Antônio Carlos Ferreira, 210 — Centro, Florianópolis/SC",
    tipo: "comprador",
    origem: "site",
    corretorId: "u2",
    orcamentoMin: 3200000,
    orcamentoMax: 4000000,
    interesses: ["compra"],
    preferencias: {
      tipos: ["casa"],
      regioes: ["Pedra Branca", "Jardim Eldorado"],
      dormitoriosMin: 3,
      vagasMin: 2,
      areaMinima: 280,
      caracteristicas: ["Piscina aquecida", "Espaço gourmet", "Automação residencial"],
    },
    etapa: "visita",
    timeline: [
      {
        id: "i1",
        tipo: "mensagem",
        titulo: "Contato recebido pelo site",
        detalhe: "Interesse na Casa Reserva da Pedra (PG-042) via formulário do anúncio.",
        data: momento(-9, "10:42"),
        autorId: "u2",
      },
      {
        id: "i2",
        tipo: "ligacao",
        titulo: "Ligação de qualificação — 14 min",
        detalhe:
          "Família de quatro pessoas, mudança prevista para janeiro. Orçamento até R$ 4 mi, financiamento pré-aprovado na Caixa.",
        data: momento(-8, "15:10"),
        autorId: "u2",
      },
      {
        id: "i3",
        tipo: "documento",
        titulo: "Book do imóvel enviado por e-mail",
        data: momento(-8, "16:02"),
        autorId: "u2",
      },
      {
        id: "i4",
        tipo: "visita",
        titulo: "Visita agendada para a Casa Reserva da Pedra",
        detalhe: "Presencial, com o casal. Confirmada por WhatsApp.",
        data: momento(-2, "11:20"),
        autorId: "u2",
      },
    ],
    documentos: [
      { id: "dc1", nome: "Pre-aprovacao-credito.pdf", tipo: "pdf", tamanhoKb: 320, enviadoEm: dia(-7) },
    ],
    favoritos: ["im1", "im6"],
    recomendados: ["im1", "im6", "im10"],
    observacoes: "Prefere visitas no período da manhã. Tem cachorro de grande porte.",
    criadoEm: dia(-9),
    atualizadoEm: dia(-2),
  },
  {
    id: "c2",
    nome: "Lucas Faria",
    documento: "42199873021",
    telefone: "48992345602",
    whatsapp: "48992345602",
    email: "lucas.faria@email.com.br",
    tipo: "locatario",
    origem: "whatsapp",
    corretorId: "u3",
    orcamentoMin: 1800,
    orcamentoMax: 2800,
    interesses: ["aluguel"],
    preferencias: {
      tipos: ["apartamento"],
      regioes: ["Pagani", "Passa Vinte", "Ponte do Imaruim"],
      dormitoriosMin: 2,
      vagasMin: 1,
      caracteristicas: ["Varanda", "Academia no condomínio"],
    },
    etapa: "contato",
    timeline: [
      {
        id: "i5",
        tipo: "mensagem",
        titulo: "Pedido de contato via WhatsApp",
        detalhe: "Procura apartamento para locação com entrada em até 60 dias.",
        data: momento(-1, "09:15"),
        autorId: "u3",
      },
      {
        id: "i6",
        tipo: "ligacao",
        titulo: "Primeira ligação — 6 min",
        detalhe: "Trabalha em Florianópolis, quer ficar a até 30 min de deslocamento.",
        data: momento(-1, "14:30"),
        autorId: "u3",
      },
    ],
    documentos: [],
    favoritos: ["im5"],
    recomendados: ["im5", "im11", "im3"],
    criadoEm: dia(-1),
    atualizadoEm: dia(-1),
  },
  {
    id: "c3",
    nome: "Camila Rocha",
    documento: "31088452190",
    telefone: "48993456703",
    whatsapp: "48993456703",
    email: "camila.rocha@email.com.br",
    tipo: "comprador",
    origem: "indicacao",
    corretorId: "u4",
    orcamentoMin: 380000,
    orcamentoMax: 520000,
    interesses: ["compra"],
    preferencias: {
      tipos: ["apartamento"],
      regioes: ["Passa Vinte", "Pagani", "Jardim Eldorado"],
      dormitoriosMin: 2,
      vagasMin: 1,
      areaMinima: 60,
      caracteristicas: ["Varanda integrada", "Armários planejados"],
    },
    etapa: "qualificado",
    timeline: [
      {
        id: "i7",
        tipo: "observacao",
        titulo: "Indicada por cliente da carteira",
        detalhe: "Indicação de Roberto Moraes (proprietário PG-042).",
        data: momento(-16, "10:00"),
        autorId: "u4",
      },
      {
        id: "i8",
        tipo: "ligacao",
        titulo: "Qualificação concluída — 22 min",
        detalhe: "Venda do apartamento atual já contratada. Recursos disponíveis em 45 dias.",
        data: momento(-14, "11:40"),
        autorId: "u4",
      },
      {
        id: "i9",
        tipo: "email",
        titulo: "Enviada seleção com 3 opções no Passa Vinte",
        data: momento(-6, "08:50"),
        autorId: "u4",
      },
    ],
    documentos: [],
    favoritos: ["im5"],
    recomendados: ["im5"],
    criadoEm: dia(-16),
    atualizadoEm: dia(-6),
  },
  {
    id: "c4",
    nome: "Paulo Teles",
    documento: "27655310088",
    telefone: "48994567804",
    whatsapp: "48994567804",
    email: "paulo.teles@email.com.br",
    tipo: "investidor",
    origem: "portal",
    corretorId: "u2",
    orcamentoMin: 180000,
    orcamentoMax: 750000,
    interesses: ["investimento", "compra"],
    preferencias: {
      tipos: ["apartamento", "comercial", "terreno"],
      regioes: ["Centro", "Pagani", "Pedra Branca"],
      caracteristicas: ["Alta liquidez", "Bom histórico de valorização"],
    },
    etapa: "proposta",
    timeline: [
      {
        id: "i10",
        tipo: "mensagem",
        titulo: "Lead recebido de portal parceiro",
        data: momento(-24, "13:05"),
        autorId: "u2",
      },
      {
        id: "i11",
        tipo: "visita",
        titulo: "Visita realizada — Terreno Pedra Branca",
        detalhe: "Avaliou a topografia com arquiteto. Interesse confirmado.",
        data: momento(-10, "10:00"),
        autorId: "u2",
      },
      {
        id: "i12",
        tipo: "proposta",
        titulo: "Proposta enviada: R$ 640.000",
        detalhe: "Pagamento à vista, com escritura em 30 dias. Aguardando retorno do proprietário.",
        data: momento(-3, "17:25"),
        autorId: "u2",
      },
    ],
    documentos: [
      { id: "dc2", nome: "Proposta-PG-036.pdf", tipo: "pdf", tamanhoKb: 180, enviadoEm: dia(-3) },
    ],
    favoritos: ["im7", "im8"],
    recomendados: ["im7", "im8", "im5"],
    observacoes: "Investidor recorrente. Já fechou duas operações com a Paganelli em 2025.",
    criadoEm: dia(-24),
    atualizadoEm: dia(-3),
  },
  {
    id: "c5",
    nome: "Renata e Marcos Ferraz",
    documento: "40922178033",
    telefone: "48995678905",
    whatsapp: "48995678905",
    email: "renata.ferraz@email.com.br",
    tipo: "comprador",
    origem: "site",
    corretorId: "u1",
    orcamentoMin: 1100000,
    orcamentoMax: 1400000,
    interesses: ["compra"],
    preferencias: {
      tipos: ["casa"],
      regioes: ["Jardim Eldorado", "Bela Vista"],
      dormitoriosMin: 3,
      vagasMin: 2,
      areaMinima: 190,
      caracteristicas: ["Piscina", "Jardim projetado", "Escritório"],
    },
    etapa: "visita",
    timeline: [
      {
        id: "i13",
        tipo: "mensagem",
        titulo: "Solicitação de visita pelo site",
        detalhe: "Casa Jardim Eldorado (PG-041).",
        data: momento(-5, "20:14"),
        autorId: "u1",
      },
      {
        id: "i14",
        tipo: "ligacao",
        titulo: "Confirmação de agenda — 4 min",
        data: momento(-4, "09:30"),
        autorId: "u1",
      },
    ],
    documentos: [],
    favoritos: ["im2"],
    recomendados: ["im2", "im6"],
    criadoEm: dia(-5),
    atualizadoEm: dia(-4),
  },
  {
    id: "c6",
    nome: "André Ribeiro",
    documento: "35411206077",
    telefone: "48996789006",
    whatsapp: "48996789006",
    email: "andre.ribeiro@email.com.br",
    tipo: "comprador",
    origem: "instagram",
    corretorId: "u4",
    orcamentoMin: 1600000,
    orcamentoMax: 1900000,
    interesses: ["compra"],
    preferencias: {
      tipos: ["casa"],
      regioes: ["Forquilhinhas", "Pedra Branca"],
      dormitoriosMin: 4,
      vagasMin: 3,
      caracteristicas: ["Piscina", "Espaço gourmet", "Horta"],
    },
    etapa: "negociacao",
    timeline: [
      {
        id: "i15",
        tipo: "mensagem",
        titulo: "Contato por anúncio no Instagram",
        data: momento(-38, "19:40"),
        autorId: "u4",
      },
      {
        id: "i16",
        tipo: "visita",
        titulo: "Segunda visita — Casa Bosque das Mangueiras",
        detalhe: "Retornou com a esposa e o arquiteto para avaliar reforma da cozinha.",
        data: momento(-15, "16:00"),
        autorId: "u4",
      },
      {
        id: "i17",
        tipo: "proposta",
        titulo: "Proposta aceita: R$ 1.690.000",
        detalhe: "Sinal pago. Imóvel reservado. Documentação em análise jurídica.",
        data: momento(-9, "12:10"),
        autorId: "u4",
      },
    ],
    documentos: [
      { id: "dc3", nome: "Contrato-preliminar-PG-037.pdf", tipo: "pdf", tamanhoKb: 640, enviadoEm: dia(-9) },
    ],
    favoritos: ["im6"],
    recomendados: ["im6"],
    criadoEm: dia(-38),
    atualizadoEm: dia(-9),
  },

  {
    id: "c19",
    nome: "Sofia Rezende",
    documento: "45733120099",
    telefone: "48997890107",
    whatsapp: "48997890107",
    email: "sofia.rezende@email.com.br",
    tipo: "comprador",
    origem: "site",
    corretorId: "u2",
    orcamentoMin: 350000,
    orcamentoMax: 500000,
    interesses: ["compra"],
    preferencias: {
      tipos: ["apartamento"],
      regioes: ["Pagani", "Passa Vinte"],
      dormitoriosMin: 2,
      vagasMin: 1,
      caracteristicas: ["Varanda"],
    },
    etapa: "novo",
    timeline: [
      {
        id: "i18",
        tipo: "mensagem",
        titulo: "Contato recebido pelo site",
        detalhe: "Primeiro imóvel. Quer entender o processo de financiamento antes de visitar.",
        data: momento(0, "07:40"),
        autorId: "u2",
      },
    ],
    documentos: [],
    favoritos: [],
    recomendados: ["im5"],
    criadoEm: dia(0),
    atualizadoEm: dia(0),
  },
  {
    id: "c20",
    nome: "Fábio e Letícia Andrade",
    documento: "29844517062",
    telefone: "48998901208",
    whatsapp: "48998901208",
    email: "fabio.andrade@email.com.br",
    tipo: "comprador",
    origem: "indicacao",
    corretorId: "u1",
    orcamentoMin: 1100000,
    orcamentoMax: 1400000,
    interesses: ["compra"],
    preferencias: {
      tipos: ["apartamento"],
      regioes: ["Jardim Eldorado", "Bela Vista"],
      dormitoriosMin: 3,
      vagasMin: 2,
      caracteristicas: [],
    },
    etapa: "fechado",
    timeline: [
      {
        id: "i19",
        tipo: "observacao",
        titulo: "Indicação de cliente da carteira",
        data: momento(-112, "10:00"),
        autorId: "u1",
      },
      {
        id: "i20",
        tipo: "visita",
        titulo: "Visita realizada — Casa no Jardim Eldorado",
        detalhe: "Segunda visita, com os pais. Decisão tomada no mesmo dia.",
        data: momento(-74, "15:00"),
        autorId: "u1",
      },
      {
        id: "i21",
        tipo: "proposta",
        titulo: "Proposta aceita: R$ 1.240.000",
        data: momento(-68, "11:30"),
        autorId: "u1",
      },
      {
        id: "i22",
        tipo: "documento",
        titulo: "Escritura registrada — negócio concluído",
        detalhe: "Comissão de 6% faturada. Cliente indicou dois novos contatos.",
        data: momento(-31, "16:20"),
        autorId: "u1",
      },
    ],
    documentos: [
      { id: "dc4", nome: "Escritura-registrada.pdf", tipo: "pdf", tamanhoKb: 980, enviadoEm: dia(-31) },
    ],
    favoritos: [],
    recomendados: [],
    observacoes: "Negócio concluído. Manter na base para indicações e futura recompra.",
    criadoEm: dia(-112),
    atualizadoEm: dia(-31),
  },

  /* ------------------------------------------------------ Proprietários */
  proprietario("c7", "Roberto Moraes", "u2", dia(-125)),
  proprietario("c8", "Helena Duarte", "u1", dia(-98)),
  proprietario("c9", "Sérgio Bittencourt", "u2", dia(-66)),
  proprietario("c10", "Cristina Vasconcelos", "u1", dia(-60)),
  proprietario("c11", "Eduardo Simões", "u3", dia(-44)),
  proprietario("c12", "Patrícia Nunes", "u4", dia(-80)),
  proprietario("c13", "Ricardo Assunção", "u3", dia(-36)),
  proprietario("c14", "Vitória Empreendimentos Ltda.", "u2", dia(-55), "18442097000164"),
  proprietario("c15", "Marcelo Tavares", "u4", dia(-90)),
  proprietario("c16", "Luiza Camargo", "u3", dia(-72)),
  proprietario("c17", "Antônio Peixoto", "u2", dia(-142)),
  proprietario("c18", "Família Almeida Prado", "u1", dia(-195), "22781054000109"),
];

/** Proprietários compartilham a mesma forma; só variam nome, corretor e data. */
function proprietario(
  id: string,
  nome: string,
  corretorId: string,
  criadoEm: string,
  documento?: string,
): Cliente {
  const indice = Number(id.replace("c", ""));
  return {
    id,
    nome,
    documento: documento ?? `${30000000000 + indice * 1379}`,
    telefone: `4898${String(400000 + indice * 137).slice(0, 6)}`,
    whatsapp: `4898${String(400000 + indice * 137).slice(0, 6)}`,
    email: `${nome.split(" ")[0].toLowerCase()}.proprietario@email.com.br`,
    tipo: "proprietario",
    origem: "indicacao",
    corretorId,
    interesses: ["venda"],
    preferencias: { tipos: [], regioes: [], caracteristicas: [] },
    etapa: "fechado",
    timeline: [
      {
        id: `ip${indice}`,
        tipo: "observacao",
        titulo: "Imóvel captado pela equipe Paganelli",
        data: `${criadoEm}T12:00:00.000Z`,
        autorId: corretorId,
      },
    ],
    documentos: [],
    favoritos: [],
    recomendados: [],
    criadoEm,
    atualizadoEm: criadoEm,
  };
}

export const clientePorId = (id: string) => clientes.find((c) => c.id === id);
