import type { Contrato } from "../types";
import { dia } from "./datas";

/**
 * Contratos de exclusividade. O status `vencendo` é recalculado no store a
 * partir de `dataTermino`, então aqui vale o estado registrado pela equipe.
 */
export const contratos: Contrato[] = [
  {
    id: "ct1",
    numero: "PG-2026/041",
    proprietarioId: "c7",
    imovelId: "im1",
    corretorId: "u2",
    dataInicio: dia(-173),
    dataTermino: dia(7),
    prazoMeses: 6,
    valorAnuncio: 3700000,
    comissaoPercentual: 6,
    status: "ativo",
    documentos: [
      { id: "dt1", nome: "Contrato-exclusividade-PG-2026-041.pdf", tipo: "pdf", tamanhoKb: 480, enviadoEm: dia(-173) },
      { id: "dt2", nome: "Procuracao-Roberto-Moraes.pdf", tipo: "pdf", tamanhoKb: 210, enviadoEm: dia(-170) },
    ],
    clausulasEspeciais:
      "Proprietário reserva o direito de indicar dois compradores diretos, isentos de comissão, mediante comunicação prévia por escrito.",
    observacoes: "Renovação já conversada por telefone. Proprietário sinalizou interesse em manter.",
    renovacoes: [],
    criadoEm: dia(-175),
  },
  {
    id: "ct2",
    numero: "PG-2026/038",
    proprietarioId: "c8",
    imovelId: "im2",
    corretorId: "u1",
    dataInicio: dia(-98),
    dataTermino: dia(131),
    prazoMeses: 8,
    valorAnuncio: 1290000,
    comissaoPercentual: 6,
    status: "ativo",
    documentos: [
      { id: "dt3", nome: "Contrato-exclusividade-PG-2026-038.pdf", tipo: "pdf", tamanhoKb: 455, enviadoEm: dia(-98) },
    ],
    renovacoes: [],
    criadoEm: dia(-99),
  },
  {
    id: "ct3",
    numero: "PG-2026/044",
    proprietarioId: "c10",
    imovelId: "im4",
    corretorId: "u1",
    dataInicio: dia(-58),
    dataTermino: dia(212),
    prazoMeses: 9,
    valorAnuncio: 2450000,
    comissaoPercentual: 5,
    status: "ativo",
    documentos: [
      { id: "dt4", nome: "Contrato-exclusividade-PG-2026-044.pdf", tipo: "pdf", tamanhoKb: 512, enviadoEm: dia(-58) },
    ],
    clausulasEspeciais:
      "Comissão reduzida a 5% em razão do ticket. Book fotográfico e vídeo aéreo por conta da Paganelli.",
    renovacoes: [],
    criadoEm: dia(-60),
  },
  {
    id: "ct4",
    numero: "PG-2026/046",
    proprietarioId: "c15",
    imovelId: "im9",
    corretorId: "u4",
    dataInicio: dia(-88),
    dataTermino: dia(23),
    prazoMeses: 4,
    valorAnuncio: 1480000,
    comissaoPercentual: 6,
    status: "ativo",
    documentos: [],
    observacoes: "Primeiro contrato com este proprietário. Avaliar prazo maior na renovação.",
    renovacoes: [],
    criadoEm: dia(-90),
  },
  {
    id: "ct5",
    numero: "PG-2026/049",
    proprietarioId: "c18",
    imovelId: "im12",
    corretorId: "u1",
    dataInicio: dia(-195),
    dataTermino: dia(15),
    prazoMeses: 7,
    valorAnuncio: 3200000,
    comissaoPercentual: 5,
    status: "ativo",
    documentos: [
      { id: "dt5", nome: "Contrato-exclusividade-PG-2026-049.pdf", tipo: "pdf", tamanhoKb: 690, enviadoEm: dia(-195) },
      { id: "dt6", nome: "Georreferenciamento-Sitio-Santa-Helena.pdf", tipo: "pdf", tamanhoKb: 1240, enviadoEm: dia(-190) },
    ],
    clausulasEspeciais:
      "Exclusividade limitada ao território nacional. Divulgação em portais fora de Santa Catarina depende de anuência prévia dos herdeiros.",
    renovacoes: [
      {
        id: "r1",
        data: dia(-195),
        prazoMeses: 7,
        observacao: "Renovação do contrato PG-2025/112, com ajuste de comissão de 6% para 5%.",
      },
    ],
    criadoEm: dia(-380),
  },
  {
    id: "ct6",
    numero: "PG-2026/051",
    proprietarioId: "c16",
    imovelId: "im10",
    corretorId: "u3",
    dataInicio: dia(-3),
    dataTermino: dia(177),
    prazoMeses: 6,
    valorAnuncio: 1650000,
    comissaoPercentual: 6,
    status: "aguardando_assinatura",
    documentos: [],
    observacoes: "Minuta enviada para assinatura digital. Aguardando retorno da proprietária.",
    renovacoes: [],
    criadoEm: dia(-5),
  },
  {
    id: "ct7",
    numero: "PG-2025/118",
    proprietarioId: "c17",
    imovelId: "im11",
    corretorId: "u2",
    dataInicio: dia(-380),
    dataTermino: dia(-21),
    prazoMeses: 12,
    valorAnuncio: 1900,
    comissaoPercentual: 8,
    status: "encerrado",
    documentos: [],
    observacoes: "Encerrado com a assinatura do contrato de locação. Objetivo cumprido.",
    renovacoes: [],
    criadoEm: dia(-382),
  },
  {
    id: "ct8",
    numero: "PG-2026/053",
    proprietarioId: "c12",
    imovelId: "im6",
    corretorId: "u4",
    dataInicio: dia(-2),
    dataTermino: dia(178),
    prazoMeses: 6,
    valorAnuncio: 1750000,
    comissaoPercentual: 6,
    status: "rascunho",
    documentos: [],
    observacoes: "Contrato em elaboração. Imóvel já reservado — avaliar necessidade.",
    renovacoes: [],
    criadoEm: dia(-2),
  },
];

export const contratoPorId = (id: string) => contratos.find((c) => c.id === id);
