import type { Imovel } from "../types";
import { dia } from "./datas";

const foto = (id: string, w = 1600) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&q=75`;

/**
 * Catálogo demonstrativo, ambientado na área real de atuação da empresa —
 * Palhoça e Grande Florianópolis. Bairros, tipologias e faixas de preço seguem
 * o perfil da carteira da corretora. Cobre todos os tipos, finalidades e status
 * do modelo, para que cada filtro do site e do painel tenha resultado real.
 */
export const imoveis: Imovel[] = [
  {
    id: "im1",
    codigo: "PG-042",
    titulo: "Casa Reserva da Pedra",
    slug: "casa-reserva-da-pedra-pedra-branca",
    tipo: "casa",
    finalidade: "venda",
    status: "disponivel",
    endereco: {
      logradouro: "Rua das Araucárias",
      numero: "180",
      bairro: "Pedra Branca",
      cidade: "Palhoça",
      estado: "SC",
      cep: "88137085",
      latitude: -27.6098,
      longitude: -48.6291,
    },
    valores: { venda: 3700000, condominio: 1180, iptu: 720 },
    metragens: {
      areaTotal: 512,
      areaConstruida: 330,
      dormitorios: 3,
      suites: 3,
      banheiros: 5,
      vagas: 2,
    },
    caracteristicas: [
      "Piscina aquecida",
      "Espaço gourmet",
      "Automação residencial",
      "Aquecimento solar",
      "Adega climatizada",
      "Lavabo",
    ],
    diferenciais: [
      "Arquitetura atemporal assinada",
      "Condomínio fechado no bairro planejado Pedra Branca",
      "Caminhada até a UNISUL, comércio e ciclovia",
    ],
    descricaoCurta:
      "Casa de alto padrão de 330 m² no Reserva da Pedra, com três suítes, piscina aquecida e arquitetura atemporal.",
    descricaoCompleta:
      "Implantada em terreno de 512 m² dentro do condomínio Reserva da Pedra, a casa foi desenhada para envelhecer bem: materiais nobres, volumetria limpa e caixilharia de piso a teto que dissolve a fronteira entre o living e o deck da piscina. Os ambientes sociais somam mais de 90 m² integrados, com espaço gourmet coberto e adega climatizada. As três suítes ficam no pavimento superior, todas com varanda voltada para a área verde preservada do condomínio. A casa conta com automação de iluminação e climatização, aquecimento solar e infraestrutura para carregador de veículo elétrico. O bairro planejado Pedra Branca reúne universidade, comércio, praças e ciclovia a caminhada de casa.",
    fotos: [
      foto("1600596542815-ffad4c1539a9"),
      foto("1600585154340-be6161a56a0c"),
      foto("1600607687939-ce8a6c25118c"),
      foto("1600566753190-17f0baa2a6c3"),
      foto("1484154218962-a197022b5858"),
      foto("1600573472550-8090b5e0745e"),
    ],
    videoUrl: "https://www.youtube.com/watch?v=demo-reserva-da-pedra",
    tourVirtualUrl: "https://tour.paganelliimoveis.com.br/pg-042",
    plantas: [foto("1580587771525-78b9dba3b914", 1200)],
    documentos: [
      { id: "d1", nome: "Matricula-PG-042.pdf", tipo: "pdf", tamanhoKb: 842, enviadoEm: dia(-120) },
      { id: "d2", nome: "IPTU-2026-PG-042.pdf", tipo: "pdf", tamanhoKb: 210, enviadoEm: dia(-118) },
    ],
    proprietarioId: "c7",
    corretorId: "u2",
    exclusivo: true,
    exclusividadeAte: dia(7),
    seo: {
      titulo: "Casa de alto padrão à venda na Pedra Branca — Reserva da Pedra",
      descricao:
        "Casa de 330 m² com 3 suítes, piscina aquecida e arquitetura atemporal na Pedra Branca, Palhoça/SC.",
    },
    historico: [
      { id: "h1", data: dia(-120), autorId: "u2", descricao: "Imóvel captado com exclusividade." },
      { id: "h2", data: dia(-46), autorId: "u2", descricao: "Valor ajustado de R$ 3.950.000 para R$ 3.700.000." },
      { id: "h3", data: dia(-12), autorId: "u1", descricao: "Novo book fotográfico publicado." },
    ],
    criadoEm: dia(-120),
  },
  {
    id: "im2",
    codigo: "PG-041",
    titulo: "Casa Jardim Eldorado",
    slug: "casa-jardim-eldorado-palhoca",
    tipo: "casa",
    finalidade: "venda",
    status: "disponivel",
    endereco: {
      logradouro: "Rua dos Ipês",
      numero: "77",
      bairro: "Jardim Eldorado",
      cidade: "Palhoça",
      estado: "SC",
      cep: "88133500",
      latitude: -27.6503,
      longitude: -48.6712,
    },
    valores: { venda: 1290000, condominio: 480, iptu: 320 },
    metragens: {
      areaTotal: 360,
      areaConstruida: 214,
      dormitorios: 3,
      suites: 1,
      banheiros: 3,
      vagas: 2,
    },
    caracteristicas: [
      "Piscina",
      "Churrasqueira",
      "Jardim projetado",
      "Armários planejados",
      "Escritório",
    ],
    diferenciais: [
      "Condomínio fechado com portaria 24 horas",
      "Rua sem saída, silenciosa",
      "10 minutos do acesso à BR-101",
    ],
    descricaoCurta:
      "Casa de 214 m² em condomínio fechado no Jardim Eldorado, com três dormitórios, piscina e escritório independente.",
    descricaoCompleta:
      "Casa térrea e sobrado combinados em um partido compacto e bem resolvido. No térreo, estar e jantar se abrem por portas de correr para o jardim projetado e a piscina, com churrasqueira coberta ao lado. Ainda no térreo há um escritório com entrada independente — solução prática para quem atende clientes em casa. No pavimento superior ficam os três dormitórios, sendo um suíte com closet. Todos os ambientes têm armários planejados. O condomínio tem portaria 24 horas, playground e fica em rua sem saída, o que garante silêncio, a dez minutos do acesso à BR-101.",
    fotos: [
      foto("1600585152915-d208bec867a1"),
      foto("1600047509807-ba8f99d2cdde"),
      foto("1522708323590-d24dbb6b0267"),
      foto("1600121848594-d8644e57abab"),
      foto("1600566752355-35792bedcfea"),
    ],
    plantas: [],
    documentos: [
      { id: "d3", nome: "Matricula-PG-041.pdf", tipo: "pdf", tamanhoKb: 760, enviadoEm: dia(-95) },
    ],
    proprietarioId: "c8",
    corretorId: "u1",
    exclusivo: true,
    exclusividadeAte: dia(131),
    seo: {
      titulo: "Casa à venda no Jardim Eldorado — Palhoça/SC",
      descricao: "Casa de 214 m² com 3 dormitórios, piscina e escritório em condomínio fechado.",
    },
    historico: [
      { id: "h4", data: dia(-95), autorId: "u1", descricao: "Imóvel captado com exclusividade." },
      { id: "h5", data: dia(-30), autorId: "u1", descricao: "Anúncio publicado no site institucional." },
    ],
    criadoEm: dia(-95),
  },
  {
    id: "im3",
    codigo: "PG-040",
    titulo: "Apartamento Residencial Taranto",
    slug: "apartamento-residencial-taranto-pagani",
    tipo: "apartamento",
    finalidade: "aluguel",
    status: "disponivel",
    endereco: {
      logradouro: "Avenida Atílio Pedro Pagani",
      numero: "420",
      complemento: "Apto 1201",
      bairro: "Pagani",
      cidade: "Palhoça",
      estado: "SC",
      cep: "88132148",
      latitude: -27.6371,
      longitude: -48.6702,
    },
    valores: { aluguel: 3800, condominio: 620, iptu: 210 },
    metragens: {
      areaTotal: 74,
      areaConstruida: 74,
      dormitorios: 2,
      suites: 1,
      banheiros: 2,
      vagas: 1,
      andar: 12,
    },
    caracteristicas: [
      "Mobiliado",
      "Sacada com churrasqueira",
      "Ar-condicionado",
      "Academia no condomínio",
      "Salão de festas",
    ],
    diferenciais: [
      "Andar alto com vista para o continente",
      "Mobiliado e pronto para morar",
      "Comércio, farmácia e mercado na quadra",
    ],
    descricaoCurta:
      "Apartamento mobiliado de 74 m² no Pagani, com dois dormitórios, suíte e sacada com churrasqueira.",
    descricaoCompleta:
      "No 12º andar do Residencial Taranto, este apartamento de 74,66 m² é entregue integralmente mobiliado e equipado — basta chegar com as malas. A planta acomoda dois dormitórios, sendo um suíte, com armários planejados em todos os ambientes. A sala se conecta à sacada com churrasqueira, voltada para o continente. O condomínio oferece academia equipada, salão de festas, espaço gourmet e portaria 24 horas. A localização é uma das mais práticas de Palhoça: mercado, farmácia, padaria e restaurantes na mesma quadra, com acesso rápido à BR-101 e a Florianópolis.",
    fotos: [
      foto("1600210492486-724fe5c67fb0"),
      foto("1502672260266-1c1ef2d93688"),
      foto("1560448204-e02f11c3d0e2"),
      foto("1493809842364-78817add7ffb"),
    ],
    plantas: [],
    documentos: [],
    proprietarioId: "c9",
    corretorId: "u2",
    exclusivo: false,
    seo: {
      titulo: "Apartamento mobiliado para alugar no Pagani — Palhoça/SC",
      descricao: "74 m², 2 dormitórios com suíte, mobiliado, no Residencial Taranto.",
    },
    historico: [
      { id: "h6", data: dia(-64), autorId: "u2", descricao: "Imóvel cadastrado para locação." },
    ],
    criadoEm: dia(-64),
  },
  {
    id: "im4",
    codigo: "PG-039",
    titulo: "Cobertura Vista Baía Sul",
    slug: "cobertura-vista-baia-sul-ponte-do-imaruim",
    tipo: "cobertura",
    finalidade: "venda",
    status: "disponivel",
    endereco: {
      logradouro: "Rua Manoel Antônio Vieira",
      numero: "560",
      complemento: "Cobertura 01",
      bairro: "Ponte do Imaruim",
      cidade: "Palhoça",
      estado: "SC",
      cep: "88130100",
      latitude: -27.6462,
      longitude: -48.6564,
    },
    valores: { venda: 2450000, condominio: 980, iptu: 640 },
    metragens: {
      areaTotal: 218,
      areaConstruida: 218,
      dormitorios: 3,
      suites: 3,
      banheiros: 4,
      vagas: 3,
      andar: 14,
    },
    caracteristicas: [
      "Terraço com piscina",
      "Espaço gourmet",
      "Hidromassagem",
      "Automação",
      "Home office",
    ],
    diferenciais: [
      "Terraço privativo de 80 m² com vista para a Baía Sul",
      "Três vagas cobertas e depósito privativo",
      "Reforma integral concluída em 2025",
    ],
    descricaoCurta:
      "Cobertura duplex de 218 m² na Ponte do Imaruim, com terraço privativo, piscina e vista para a Baía Sul.",
    descricaoCompleta:
      "Cobertura duplex que ocupa sozinha o último pavimento do edifício. No nível inferior, o living de 55 m² recebe luz por duas faces e se integra ao jantar e à cozinha gourmet; as três suítes ficam na ala íntima, protegidas do movimento social, e a máster tem closet e banheira. O nível superior é inteiramente dedicado ao lazer: terraço de 80 m² com piscina, hidromassagem, espaço gourmet coberto e vista aberta para a Baía Sul e a ponte Hercílio Luz ao fundo. Reforma integral concluída em 2025, com automação de iluminação e persianas. Três vagas cobertas e depósito privativo.",
    fotos: [
      foto("1512917774080-9991f1c4c750"),
      foto("1600607687920-4e2a09cf159d"),
      foto("1600585153490-76fb20a32601"),
      foto("1505873242700-f289a29e1e0f"),
      foto("1523217582562-09d0def993a6"),
    ],
    tourVirtualUrl: "https://tour.paganelliimoveis.com.br/pg-039",
    plantas: [],
    documentos: [],
    proprietarioId: "c10",
    corretorId: "u1",
    exclusivo: true,
    exclusividadeAte: dia(212),
    seo: {
      titulo: "Cobertura à venda na Ponte do Imaruim — vista para a Baía Sul",
      descricao: "Cobertura duplex de 218 m² com terraço, piscina e 3 suítes em Palhoça/SC.",
    },
    historico: [
      { id: "h7", data: dia(-58), autorId: "u1", descricao: "Imóvel captado com exclusividade." },
    ],
    criadoEm: dia(-58),
  },
  {
    id: "im5",
    codigo: "PG-038",
    titulo: "Apartamento Nova Cidade",
    slug: "apartamento-nova-cidade-passa-vinte",
    tipo: "apartamento",
    finalidade: "ambos",
    status: "disponivel",
    endereco: {
      logradouro: "Rua Domingos Bernardo Coelho",
      numero: "1180",
      complemento: "Apto 304",
      bairro: "Passa Vinte",
      cidade: "Palhoça",
      estado: "SC",
      cep: "88132100",
      latitude: -27.6455,
      longitude: -48.6798,
    },
    valores: { venda: 465000, aluguel: 2200, condominio: 420, iptu: 160 },
    metragens: {
      areaTotal: 68,
      areaConstruida: 68,
      dormitorios: 2,
      suites: 1,
      banheiros: 2,
      vagas: 1,
      andar: 3,
    },
    caracteristicas: [
      "Semi mobiliado",
      "Sacada",
      "Armários planejados",
      "Playground",
      "Salão de festas",
    ],
    diferenciais: [
      "Semi mobiliado, com planejados em todos os ambientes",
      "Vaga coberta e depósito",
      "Escolas e creche a menos de 500 m",
    ],
    descricaoCurta:
      "Apartamento semi mobiliado de 68 m² no Passa Vinte, com dois dormitórios e suíte — disponível para venda ou locação.",
    descricaoCompleta:
      "Apartamento bem-resolvido no bairro Nova Cidade, em Passa Vinte. São 68 m² com dois dormitórios, sendo um suíte, todos com armários planejados, além de sala integrada à cozinha e sacada. O imóvel é entregue semi mobiliado, o que reduz de forma relevante o custo de mudança. O condomínio tem playground, salão de festas, bicicletário e portaria. A região é consolidada e tranquila, com escolas, creche, mercado e ponto de ônibus a menos de 500 metros, e acesso rápido à BR-101.",
    fotos: [
      foto("1560185007-cde436f6a4d0"),
      foto("1502005229762-cf1b2da7c5d6"),
      foto("1484154218962-a197022b5858"),
      foto("1493809842364-78817add7ffb"),
    ],
    plantas: [],
    documentos: [],
    proprietarioId: "c11",
    corretorId: "u3",
    exclusivo: false,
    seo: {
      titulo: "Apartamento no Passa Vinte — 2 dormitórios com suíte",
      descricao: "68 m² semi mobiliado, 2 dormitórios e vaga em Palhoça/SC. Venda ou locação.",
    },
    historico: [
      { id: "h8", data: dia(-41), autorId: "u3", descricao: "Imóvel cadastrado para venda e locação." },
    ],
    criadoEm: dia(-41),
  },
  {
    id: "im6",
    codigo: "PG-037",
    titulo: "Casa Bosque das Mangueiras",
    slug: "casa-bosque-das-mangueiras-sao-jose",
    tipo: "casa",
    finalidade: "venda",
    status: "reservado",
    endereco: {
      logradouro: "Rua das Mangueiras",
      numero: "245",
      bairro: "Forquilhinhas",
      cidade: "São José",
      estado: "SC",
      cep: "88106500",
      latitude: -27.5793,
      longitude: -48.6421,
    },
    valores: { venda: 1750000, condominio: 690, iptu: 430 },
    metragens: {
      areaTotal: 480,
      areaConstruida: 268,
      dormitorios: 4,
      suites: 2,
      banheiros: 4,
      vagas: 3,
    },
    caracteristicas: ["Piscina", "Espaço gourmet", "Horta", "Lareira", "Poço artesiano"],
    diferenciais: [
      "Terreno arborizado com mangueiras antigas",
      "Condomínio com trilha e área de convívio",
      "15 minutos do centro de São José",
    ],
    descricaoCurta:
      "Casa de 268 m² em condomínio de Forquilhinhas, com quatro dormitórios, piscina e terreno arborizado.",
    descricaoCompleta:
      "O projeto aproveitou as mangueiras antigas do terreno de 480 m² e organizou a casa ao redor delas, garantindo sombra natural na área de lazer durante todo o verão. No térreo ficam os ambientes sociais, a cozinha integrada e o espaço gourmet voltado para a piscina; no pavimento superior, quatro dormitórios, sendo dois suítes. Há ainda horta produtiva, lareira na sala de estar e poço artesiano. O condomínio, de baixa densidade, tem trilha interna, área de convívio e portaria 24 horas, a quinze minutos do centro de São José.",
    fotos: [
      foto("1568605114967-8130f3a36994"),
      foto("1570129477492-45c003edd2be"),
      foto("1600573472550-8090b5e0745e"),
      foto("1449844908441-8829872d2607"),
    ],
    plantas: [],
    documentos: [],
    proprietarioId: "c12",
    corretorId: "u4",
    exclusivo: false,
    seo: {
      titulo: "Casa à venda em Forquilhinhas — São José/SC",
      descricao: "268 m² com piscina, espaço gourmet e horta em condomínio arborizado.",
    },
    historico: [
      { id: "h9", data: dia(-77), autorId: "u4", descricao: "Imóvel cadastrado." },
      { id: "h10", data: dia(-9), autorId: "u4", descricao: "Status alterado para reservado após proposta aceita." },
    ],
    criadoEm: dia(-77),
  },
  {
    id: "im7",
    codigo: "PG-036",
    titulo: "Terreno Pedra Branca",
    slug: "terreno-pedra-branca-palhoca",
    tipo: "terreno",
    finalidade: "venda",
    status: "disponivel",
    endereco: {
      logradouro: "Rua Adhemar da Silva",
      numero: "s/n",
      complemento: "Lote 18, Quadra F",
      bairro: "Pedra Branca",
      cidade: "Palhoça",
      estado: "SC",
      cep: "88137090",
      latitude: -27.6122,
      longitude: -48.6335,
    },
    valores: { venda: 690000, condominio: 380, iptu: 190 },
    metragens: {
      areaTotal: 420,
      dormitorios: 0,
      suites: 0,
      banheiros: 0,
      vagas: 0,
    },
    caracteristicas: ["Terreno plano", "Esquina", "Infraestrutura completa"],
    diferenciais: [
      "Um dos últimos lotes de esquina do quarteirão",
      "Topografia plana, sem necessidade de contenção",
      "Dentro do bairro planejado Pedra Branca",
    ],
    descricaoCurta:
      "Lote plano de esquina com 420 m² no bairro planejado Pedra Branca, com infraestrutura completa e pronto para construir.",
    descricaoCompleta:
      "Terreno de 420 m² em uma das últimas esquinas disponíveis do quarteirão. A topografia é integralmente plana, o que dispensa muros de arrimo e reduz o custo de fundação. A infraestrutura do loteamento está concluída — água, esgoto, energia e fibra óptica na testada, com calçada e arborização entregues. O Pedra Branca é um bairro planejado de uso misto, com universidade, comércio de rua, praças, ciclovia e transporte público integrado, o que sustenta a valorização do lote no médio prazo. Documentação regular e pronta para transferência.",
    fotos: [foto("1500382017468-9049fed747ef"), foto("1449844908441-8829872d2607")],
    plantas: [],
    documentos: [],
    proprietarioId: "c13",
    corretorId: "u3",
    exclusivo: false,
    seo: {
      titulo: "Terreno à venda na Pedra Branca — Palhoça/SC",
      descricao: "Lote plano de esquina com 420 m² e infraestrutura completa.",
    },
    historico: [{ id: "h11", data: dia(-33), autorId: "u3", descricao: "Imóvel cadastrado." }],
    criadoEm: dia(-33),
  },
  {
    id: "im8",
    codigo: "PG-035",
    titulo: "Sala Comercial Hogar Corporate",
    slug: "sala-comercial-hogar-corporate-centro",
    tipo: "comercial",
    finalidade: "ambos",
    status: "disponivel",
    endereco: {
      logradouro: "Avenida Barão do Rio Branco",
      numero: "390",
      complemento: "Sala 1408",
      bairro: "Centro",
      cidade: "Palhoça",
      estado: "SC",
      cep: "88130200",
      latitude: -27.6452,
      longitude: -48.6693,
    },
    valores: { venda: 212000, aluguel: 1600, condominio: 480, iptu: 210 },
    metragens: {
      areaTotal: 21,
      areaConstruida: 21,
      dormitorios: 0,
      suites: 0,
      banheiros: 1,
      vagas: 1,
      andar: 14,
    },
    caracteristicas: [
      "Ar-condicionado",
      "Banheiro privativo",
      "Recepção compartilhada",
      "Segurança 24h",
      "Elevadores sociais",
    ],
    diferenciais: [
      "Excelente liquidez para locação corporativa",
      "Vaga privativa na garagem",
      "No centro de Palhoça, ao lado dos órgãos públicos",
    ],
    descricaoCurta:
      "Sala comercial de 20,60 m² no Hogar Corporate, no centro de Palhoça — boa opção de investimento com liquidez.",
    descricaoCompleta:
      "Sala de 20,60 m² no 14º andar do Hogar Corporate, o edifício corporativo mais bem posicionado do centro de Palhoça. A unidade é entregue com ar-condicionado, banheiro privativo e ponto de rede, pronta para receber o layout do inquilino. O edifício tem recepção compartilhada, controle de acesso, segurança 24 horas e elevadores sociais. A localização, ao lado dos órgãos públicos e do comércio central, sustenta a demanda constante por locação — perfil de imóvel com boa liquidez e baixa vacância. Acompanha uma vaga privativa na garagem.",
    fotos: [
      foto("1497366754035-f200968a6e72"),
      foto("1497366811353-6870744d04b2"),
      foto("1524758631624-e2822e304c36"),
    ],
    plantas: [],
    documentos: [],
    proprietarioId: "c14",
    corretorId: "u2",
    exclusivo: false,
    seo: {
      titulo: "Sala comercial à venda no centro de Palhoça — Hogar Corporate",
      descricao: "20,60 m² com vaga privativa em edifício corporativo. Venda ou locação.",
    },
    historico: [{ id: "h12", data: dia(-52), autorId: "u2", descricao: "Imóvel cadastrado." }],
    criadoEm: dia(-52),
  },
  {
    id: "im9",
    codigo: "PG-034",
    titulo: "Apartamento Frente Mar Enseada",
    slug: "apartamento-frente-mar-enseada-de-brito",
    tipo: "apartamento",
    finalidade: "venda",
    status: "disponivel",
    endereco: {
      logradouro: "Avenida Beira Mar",
      numero: "340",
      complemento: "Apto 901",
      bairro: "Enseada de Brito",
      cidade: "Palhoça",
      estado: "SC",
      cep: "88138000",
      latitude: -27.7398,
      longitude: -48.6252,
    },
    valores: { venda: 1480000, condominio: 780, iptu: 460 },
    metragens: {
      areaTotal: 132,
      areaConstruida: 132,
      dormitorios: 3,
      suites: 2,
      banheiros: 3,
      vagas: 2,
      andar: 9,
    },
    caracteristicas: [
      "Vista permanente para o mar",
      "Sacada com churrasqueira",
      "Piscina no condomínio",
      "Dependência completa",
      "Dois elevadores",
    ],
    diferenciais: [
      "Frente mar, com vista permanente",
      "Apenas dois apartamentos por andar",
      "Duas vagas cobertas demarcadas",
    ],
    descricaoCurta:
      "Apartamento frente mar de 132 m² na Enseada de Brito, com três dormitórios, duas suítes e vista permanente.",
    descricaoCompleta:
      "No 9º andar de um edifício com apenas duas unidades por pavimento, este apartamento de 132 m² tem a vista que não se compra duas vezes: mar aberto pela frente, sem possibilidade de construção que a obstrua. O living em L acomoda estar e jantar sem disputa de espaço e se abre para a sacada com churrasqueira. São três dormitórios, dois deles suítes, além de dependência completa. O condomínio tem piscina, salão de festas, academia e dois elevadores. Duas vagas cobertas demarcadas e depósito privativo.",
    fotos: [
      foto("1600566753086-00f18fb6b3ea"),
      foto("1600585153490-76fb20a32601"),
      foto("1522708323590-d24dbb6b0267"),
      foto("1560448204-e02f11c3d0e2"),
      foto("1502005229762-cf1b2da7c5d6"),
    ],
    plantas: [],
    documentos: [],
    proprietarioId: "c15",
    corretorId: "u4",
    exclusivo: true,
    exclusividadeAte: dia(23),
    seo: {
      titulo: "Apartamento frente mar à venda na Enseada de Brito — Palhoça/SC",
      descricao: "132 m², 3 dormitórios com 2 suítes e vista permanente para o mar.",
    },
    historico: [{ id: "h13", data: dia(-88), autorId: "u4", descricao: "Imóvel captado com exclusividade." }],
    criadoEm: dia(-88),
  },
  {
    id: "im10",
    codigo: "PG-033",
    titulo: "Casa de Campo Serra do Tabuleiro",
    slug: "casa-de-campo-serra-do-tabuleiro",
    tipo: "casa",
    finalidade: "venda",
    status: "disponivel",
    endereco: {
      logradouro: "Estrada Geral da Guarda",
      numero: "1500",
      bairro: "Guarda do Cubatão",
      cidade: "Palhoça",
      estado: "SC",
      cep: "88135000",
      latitude: -27.7185,
      longitude: -48.7402,
    },
    valores: { venda: 1650000, iptu: 380 },
    metragens: {
      areaTotal: 5200,
      areaConstruida: 320,
      dormitorios: 4,
      suites: 2,
      banheiros: 4,
      vagas: 4,
    },
    caracteristicas: [
      "Piscina",
      "Lareira",
      "Pomar",
      "Poço artesiano",
      "Casa de caseiro",
      "Nascente própria",
    ],
    diferenciais: [
      "Terreno de 5.200 m² com nascente própria",
      "Vista para a Serra do Tabuleiro",
      "25 minutos do centro de Palhoça",
    ],
    descricaoCurta:
      "Casa de campo de 320 m² na Guarda do Cubatão, com 5.200 m² de terreno, pomar formado e vista para a Serra do Tabuleiro.",
    descricaoCompleta:
      "Uma casa feita para receber, a vinte e cinco minutos do centro de Palhoça. O terreno de 5.200 m² acomoda, além da residência de 320 m², piscina, pomar já formado com mais de quinze espécies frutíferas, casa de caseiro independente e nascente própria. Na casa principal, o salão com pé-direito alto e lareira central articula estar, jantar e a varanda coberta que percorre toda a fachada dos fundos, voltada para a Serra do Tabuleiro. São quatro dormitórios, dois deles suítes. Água de poço artesiano, energia trifásica e internet por fibra.",
    fotos: [
      foto("1600585154340-be6161a56a0c"),
      foto("1613490493576-7fde63acd811"),
      foto("1580587771525-78b9dba3b914"),
      foto("1600573472550-8090b5e0745e"),
    ],
    plantas: [],
    documentos: [],
    proprietarioId: "c16",
    corretorId: "u3",
    exclusivo: false,
    seo: {
      titulo: "Casa de campo à venda na Guarda do Cubatão — Palhoça/SC",
      descricao: "320 m² em terreno de 5.200 m² com pomar, nascente e vista para a Serra do Tabuleiro.",
    },
    historico: [{ id: "h14", data: dia(-70), autorId: "u3", descricao: "Imóvel cadastrado." }],
    criadoEm: dia(-70),
  },
  {
    id: "im11",
    codigo: "PG-032",
    titulo: "Apartamento Parque da Ponte",
    slug: "apartamento-parque-da-ponte-imaruim",
    tipo: "apartamento",
    finalidade: "aluguel",
    status: "alugado",
    endereco: {
      logradouro: "Rua Prefeito Nagib Jabor",
      numero: "890",
      complemento: "Apto 52",
      bairro: "Ponte do Imaruim",
      cidade: "Palhoça",
      estado: "SC",
      cep: "88130110",
      latitude: -27.6488,
      longitude: -48.6598,
    },
    valores: { aluguel: 1900, condominio: 390, iptu: 140 },
    metragens: {
      areaTotal: 48,
      areaConstruida: 48,
      dormitorios: 2,
      suites: 0,
      banheiros: 1,
      vagas: 1,
      andar: 5,
    },
    caracteristicas: ["Semi mobiliado", "Sacada", "Portaria 24h", "Playground"],
    diferenciais: ["A 400 m do terminal de ônibus", "Prédio reformado em 2024"],
    descricaoCurta:
      "Apartamento semi mobiliado de 48 m² na Ponte do Imaruim, com dois dormitórios e vaga coberta.",
    descricaoCompleta:
      "Apartamento de 48,53 m² no Parque da Ponte, com dois dormitórios, sacada e vaga coberta. O imóvel é entregue semi mobiliado, com planejados na cozinha e nos quartos. O prédio passou por reforma de fachada e áreas comuns em 2024 e conta com playground, salão de festas e portaria 24 horas. Fica a 400 metros do terminal de ônibus da Ponte do Imaruim, com acesso direto a Florianópolis — perfil muito procurado por quem trabalha na capital.",
    fotos: [foto("1493809842364-78817add7ffb"), foto("1560448204-e02f11c3d0e2")],
    plantas: [],
    documentos: [],
    proprietarioId: "c17",
    corretorId: "u2",
    exclusivo: false,
    seo: {
      titulo: "Apartamento para alugar na Ponte do Imaruim — Palhoça/SC",
      descricao: "48 m² semi mobiliado, 2 dormitórios e vaga, a 400 m do terminal.",
    },
    historico: [
      { id: "h15", data: dia(-140), autorId: "u2", descricao: "Imóvel cadastrado para locação." },
      { id: "h16", data: dia(-21), autorId: "u2", descricao: "Contrato de locação assinado. Status alterado para alugado." },
    ],
    criadoEm: dia(-140),
  },
  {
    id: "im12",
    codigo: "PG-031",
    titulo: "Sítio Santa Helena",
    slug: "sitio-santa-helena-santo-amaro-da-imperatriz",
    tipo: "fazenda",
    finalidade: "venda",
    status: "disponivel",
    endereco: {
      logradouro: "Rodovia SC-431",
      numero: "km 12",
      bairro: "Zona Rural",
      cidade: "Santo Amaro da Imperatriz",
      estado: "SC",
      cep: "88140000",
      latitude: -27.6874,
      longitude: -48.7789,
    },
    valores: { venda: 3200000, iptu: 890 },
    metragens: {
      areaTotal: 96000,
      areaConstruida: 420,
      dormitorios: 5,
      suites: 3,
      banheiros: 6,
      vagas: 6,
    },
    caracteristicas: [
      "Sede restaurada",
      "Lagoa própria",
      "Casa de hóspedes",
      "Pomar formado",
      "Pastagem formada",
      "Energia trifásica",
    ],
    diferenciais: [
      "9,6 hectares com lagoa e nascente",
      "Rio de águas limpas na divisa",
      "35 minutos de Florianópolis",
    ],
    descricaoCurta:
      "Sítio de 9,6 hectares em Santo Amaro da Imperatriz, com sede restaurada, lagoa própria e rio na divisa.",
    descricaoCompleta:
      "Propriedade de 96.000 m² — cerca de 9,6 hectares — às margens da SC-431, no vale de Santo Amaro da Imperatriz. A sede de 420 m² foi restaurada preservando as madeiras originais e hoje reúne cinco dormitórios, três deles suítes, com varanda que percorre toda a frente da casa. A propriedade conta ainda com casa de hóspedes independente, casa de caseiro, galpão de máquinas, pomar formado, lagoa própria com nascente e um rio de águas limpas na divisa. Pastagem formada, energia trifásica e documentação regular, a trinta e cinco minutos de Florianópolis.",
    fotos: [
      foto("1500382017468-9049fed747ef"),
      foto("1449844908441-8829872d2607"),
      foto("1613490493576-7fde63acd811"),
      foto("1580587771525-78b9dba3b914"),
    ],
    plantas: [],
    documentos: [],
    proprietarioId: "c18",
    corretorId: "u1",
    exclusivo: true,
    exclusividadeAte: dia(15),
    seo: {
      titulo: "Sítio à venda em Santo Amaro da Imperatriz — Santa Helena",
      descricao: "9,6 hectares com sede restaurada, lagoa própria e rio na divisa, a 35 min de Florianópolis.",
    },
    historico: [{ id: "h17", data: dia(-190), autorId: "u1", descricao: "Imóvel captado com exclusividade." }],
    criadoEm: dia(-190),
  },
];

export const imovelPorId = (id: string) => imoveis.find((i) => i.id === id);
