import type { Lead, LogAcao, Notificacao, Tarefa } from "../types";
import { dia, momento } from "./datas";

/** Leads recebidos pelo site institucional, antes de virarem clientes do CRM. */
export const leads: Lead[] = [
  {
    id: "l1",
    nome: "Juliana Marques",
    email: "juliana.marques@email.com.br",
    telefone: "48997654321",
    mensagem:
      "Tenho interesse na cobertura da Ponte do Imaruim. Posso visitar em um sábado pela manhã?",
    canal: "formulario_imovel",
    imovelId: "im4",
    anuncioId: "an4",
    status: "novo",
    criadoEm: momento(0, "08:20"),
  },
  {
    id: "l2",
    nome: "Thiago Bernardes",
    email: "thiago.bernardes@email.com.br",
    telefone: "48996543210",
    mensagem:
      "Quero anunciar meu apartamento no Pagani, 2 dormitórios com suíte, 69 m². Gostaria de uma avaliação.",
    canal: "anuncie",
    status: "novo",
    criadoEm: momento(-1, "17:45"),
  },
  {
    id: "l3",
    nome: "Aline Corrêa",
    email: "aline.correa@email.com.br",
    telefone: "48995432109",
    mensagem: "Gostaria de agendar uma visita ao apartamento frente mar da Enseada de Brito.",
    canal: "agendamento",
    imovelId: "im9",
    anuncioId: "an8",
    status: "atribuido",
    corretorId: "u4",
    criadoEm: momento(-2, "11:05"),
  },
  {
    id: "l4",
    nome: "Gustavo Pinheiro",
    email: "gustavo.pinheiro@email.com.br",
    telefone: "48994321098",
    mensagem:
      "Procuro casa em condomínio fechado em Palhoça até R$ 1,4 milhão. Podem me enviar opções?",
    canal: "formulario_contato",
    status: "em_atendimento",
    corretorId: "u1",
    criadoEm: momento(-4, "09:33"),
  },
  {
    id: "l5",
    nome: "Marina Azevedo",
    email: "marina.azevedo@email.com.br",
    telefone: "48991234501",
    mensagem: "Tenho interesse na Casa Reserva da Pedra.",
    canal: "formulario_imovel",
    imovelId: "im1",
    anuncioId: "an1",
    status: "convertido",
    corretorId: "u2",
    clienteId: "c1",
    criadoEm: momento(-9, "10:42"),
  },
  {
    id: "l6",
    nome: "Contato sem retorno",
    email: "naoinformado@email.com.br",
    telefone: "48993210987",
    mensagem: "Qual o valor do condomínio do apartamento da Ponte do Imaruim?",
    canal: "formulario_imovel",
    imovelId: "im11",
    status: "descartado",
    criadoEm: momento(-30, "22:11"),
  },
];

/** Tarefas e lembretes da equipe. */
export const tarefas: Tarefa[] = [
  {
    id: "t1",
    titulo: "Enviar simulação de financiamento para Marina Azevedo",
    vencimento: dia(0),
    concluida: false,
    responsavelId: "u2",
    clienteId: "c1",
    imovelId: "im1",
  },
  {
    id: "t2",
    titulo: "Retornar contato de Lucas Faria",
    vencimento: dia(0),
    concluida: false,
    responsavelId: "u3",
    clienteId: "c2",
  },
  {
    id: "t3",
    titulo: "Negociar renovação do contrato PG-2026/041",
    vencimento: dia(2),
    concluida: false,
    responsavelId: "u2",
    clienteId: "c7",
    imovelId: "im1",
  },
  {
    id: "t4",
    titulo: "Revisar anúncio do Sítio Santa Helena antes de publicar",
    vencimento: dia(1),
    concluida: false,
    responsavelId: "u1",
    imovelId: "im12",
  },
  {
    id: "t5",
    titulo: "Reagendar visita de Camila Rocha (não compareceu)",
    vencimento: dia(1),
    concluida: false,
    responsavelId: "u4",
    clienteId: "c3",
    imovelId: "im9",
  },
  {
    id: "t6",
    titulo: "Cobrar assinatura digital do contrato PG-2026/051",
    vencimento: dia(3),
    concluida: false,
    responsavelId: "u3",
    clienteId: "c16",
  },
  {
    id: "t7",
    titulo: "Atualizar book fotográfico da Casa Jardim Eldorado",
    vencimento: dia(-2),
    concluida: true,
    responsavelId: "u1",
    imovelId: "im2",
  },
];

export const notificacoes: Notificacao[] = [
  {
    id: "n1",
    tipo: "lead",
    titulo: "Novo lead recebido pelo site",
    descricao: "Juliana Marques demonstrou interesse na Cobertura Vista Baía Sul.",
    data: momento(0, "08:20"),
    lida: false,
    href: "/painel/leads",
  },
  {
    id: "n2",
    tipo: "contrato",
    titulo: "Contrato PG-2026/041 vence em 7 dias",
    descricao: "Casa Reserva da Pedra — proprietário Roberto Moraes.",
    data: momento(0, "07:00"),
    lida: false,
    href: "/painel/contratos",
  },
  {
    id: "n3",
    tipo: "visita",
    titulo: "Visita hoje às 15h",
    descricao: "Marina Azevedo — Casa Reserva da Pedra, portaria do condomínio.",
    data: momento(0, "07:00"),
    lida: false,
    href: "/painel/visitas",
  },
  {
    id: "n4",
    tipo: "anuncio",
    titulo: "Anúncio aguardando revisão",
    descricao: "Sítio Santa Helena está em revisão há 2 dias.",
    data: momento(-2, "16:30"),
    lida: true,
    href: "/painel/anuncios",
  },
  {
    id: "n5",
    tipo: "lead",
    titulo: "Pedido de avaliação de imóvel",
    descricao: "Thiago Bernardes quer anunciar um apartamento no Pagani.",
    data: momento(-1, "17:45"),
    lida: true,
    href: "/painel/leads",
  },
];

/** Trilha de auditoria das ações relevantes — base para o log de segurança. */
export const logs: LogAcao[] = [
  {
    id: "lg1",
    data: momento(-1, "18:02"),
    usuarioId: "u1",
    acao: "Publicou anúncio",
    entidade: "AN-008",
    detalhe: "Apartamento frente mar da Enseada de Brito publicado no site institucional.",
  },
  {
    id: "lg2",
    data: momento(-2, "16:30"),
    usuarioId: "u1",
    acao: "Enviou para revisão",
    entidade: "AN-010",
    detalhe: "Sítio Santa Helena aguardando aprovação do administrador.",
  },
  {
    id: "lg3",
    data: momento(-9, "12:10"),
    usuarioId: "u4",
    acao: "Registrou proposta",
    entidade: "PG-037",
    detalhe: "Proposta de R$ 1.690.000 aceita. Imóvel alterado para reservado.",
  },
  {
    id: "lg4",
    data: momento(-12, "09:45"),
    usuarioId: "u1",
    acao: "Atualizou imóvel",
    entidade: "PG-042",
    detalhe: "Novo book fotográfico com seis imagens.",
  },
  {
    id: "lg5",
    data: momento(-21, "14:20"),
    usuarioId: "u2",
    acao: "Encerrou contrato",
    entidade: "PG-2025/118",
    detalhe: "Locação assinada. Imóvel PG-032 alterado para alugado.",
  },
];
