import type { Visita } from "../types";
import { dia } from "./datas";

/** Agenda demonstrativa: visitas hoje, ao longo da semana e histórico recente. */
export const visitas: Visita[] = [
  {
    id: "v1",
    codigo: "VS-041",
    clienteId: "c1",
    imovelId: "im1",
    corretorId: "u2",
    data: dia(0),
    horaInicio: "15:00",
    horaFim: "16:00",
    modalidade: "presencial",
    pontoEncontro: "Portaria do condomínio Reserva da Pedra — Pedra Branca",
    status: "confirmada",
    confirmadaPeloCliente: true,
    lembreteEnviado: true,
    proximaAcao: "Enviar simulação de financiamento após a visita.",
    criadoEm: dia(-2),
  },
  {
    id: "v2",
    codigo: "VS-042",
    clienteId: "c5",
    imovelId: "im2",
    corretorId: "u1",
    data: dia(1),
    horaInicio: "14:00",
    horaFim: "15:00",
    modalidade: "presencial",
    pontoEncontro: "Portaria do condomínio — Rua dos Ipês, 77, Jardim Eldorado",
    status: "confirmada",
    confirmadaPeloCliente: true,
    lembreteEnviado: true,
    criadoEm: dia(-4),
  },
  {
    id: "v3",
    codigo: "VS-043",
    clienteId: "c3",
    imovelId: "im5",
    corretorId: "u4",
    data: dia(2),
    horaInicio: "10:30",
    horaFim: "11:15",
    modalidade: "presencial",
    pontoEncontro: "Rua Domingos Bernardo Coelho, 1180 — portaria",
    status: "agendada",
    confirmadaPeloCliente: false,
    lembreteEnviado: false,
    criadoEm: dia(-1),
  },
  {
    id: "v4",
    codigo: "VS-044",
    clienteId: "c4",
    imovelId: "im8",
    corretorId: "u2",
    data: dia(3),
    horaInicio: "09:00",
    horaFim: "10:00",
    modalidade: "presencial",
    pontoEncontro: "Recepção do Hogar Corporate — Av. Barão do Rio Branco, 390",
    status: "agendada",
    confirmadaPeloCliente: false,
    lembreteEnviado: true,
    criadoEm: dia(-2),
  },
  {
    id: "v5",
    codigo: "VS-045",
    clienteId: "c2",
    imovelId: "im3",
    corretorId: "u3",
    data: dia(4),
    horaInicio: "18:30",
    horaFim: "19:15",
    modalidade: "virtual",
    pontoEncontro: "Videochamada — link enviado por WhatsApp",
    status: "agendada",
    confirmadaPeloCliente: true,
    lembreteEnviado: false,
    criadoEm: dia(-1),
  },
  {
    id: "v6",
    codigo: "VS-046",
    clienteId: "c1",
    imovelId: "im6",
    corretorId: "u2",
    data: dia(5),
    horaInicio: "11:00",
    horaFim: "12:00",
    modalidade: "presencial",
    pontoEncontro: "Portaria do condomínio em Forquilhinhas — São José",
    status: "agendada",
    confirmadaPeloCliente: false,
    lembreteEnviado: false,
    proximaAcao: "Comparar com a Reserva da Pedra na mesma semana.",
    criadoEm: dia(0),
  },
  {
    id: "v7",
    codigo: "VS-038",
    clienteId: "c6",
    imovelId: "im6",
    corretorId: "u4",
    data: dia(-15),
    horaInicio: "16:00",
    horaFim: "17:30",
    modalidade: "presencial",
    pontoEncontro: "Portaria do condomínio em Forquilhinhas — São José",
    status: "realizada",
    confirmadaPeloCliente: true,
    lembreteEnviado: true,
    feedbackCliente:
      "Gostamos muito do terreno arborizado e da área de lazer. A cozinha precisaria de reforma, mas o restante atende.",
    observacoesCorretor:
      "Segunda visita, com arquiteto. Cliente demonstrou intenção clara de proposta.",
    proximaAcao: "Enviar minuta de proposta em 48 h.",
    criadoEm: dia(-19),
  },
  {
    id: "v8",
    codigo: "VS-036",
    clienteId: "c4",
    imovelId: "im7",
    corretorId: "u2",
    data: dia(-10),
    horaInicio: "10:00",
    horaFim: "10:45",
    modalidade: "presencial",
    pontoEncontro: "Rua Adhemar da Silva, s/n — Pedra Branca",
    status: "realizada",
    confirmadaPeloCliente: true,
    lembreteEnviado: true,
    feedbackCliente: "Topografia melhor do que eu esperava. Vou levar ao arquiteto.",
    observacoesCorretor: "Investidor bem informado. Levou medições próprias.",
    proximaAcao: "Aguardar retorno com proposta.",
    criadoEm: dia(-14),
  },
  {
    id: "v9",
    codigo: "VS-034",
    clienteId: "c3",
    imovelId: "im9",
    corretorId: "u4",
    data: dia(-8),
    horaInicio: "15:00",
    horaFim: "16:00",
    modalidade: "presencial",
    pontoEncontro: "Portaria — Av. Beira Mar, 340, Enseada de Brito",
    status: "nao_compareceu",
    confirmadaPeloCliente: true,
    lembreteEnviado: true,
    observacoesCorretor: "Cliente não compareceu e não atendeu. Reagendar por WhatsApp.",
    proximaAcao: "Reagendar visita.",
    criadoEm: dia(-12),
  },
  {
    id: "v10",
    codigo: "VS-030",
    clienteId: "c2",
    imovelId: "im11",
    corretorId: "u3",
    data: dia(-25),
    horaInicio: "19:00",
    horaFim: "19:40",
    modalidade: "presencial",
    pontoEncontro: "Rua Prefeito Nagib Jabor, 890 — Ponte do Imaruim",
    status: "cancelada",
    confirmadaPeloCliente: false,
    lembreteEnviado: true,
    observacoesCorretor: "Imóvel locado antes da visita. Cliente redirecionado para PG-040.",
    criadoEm: dia(-28),
  },
];

export const visitaPorId = (id: string) => visitas.find((v) => v.id === id);
